### ISSUE TITLE
linux orderly shutdown not noticed by xcat.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1939]
We use xdsh xxx reboot to do an orderly shutdown of our nodes.

when we do this,  xCAT fails to notice the change in status on the node.

To observe this we use a loop to watch the status of the node as is rebooted.
on one terminal we issue:

```
while true; do 
  date | tr -d '\n'; echo -n " "; 
  lsdef c460c002 -i status -c; 
  sleep 5;
done                                                                              
```

On another terminal we issue 
date ; xdsh c460c002 reboot;

Where we see:

```
Wed Oct  5 08:05:58 EDT 2016
c460c002: Connection to c460c002 closed by remote host.
```

Watching the boot sequence on the first terminal we see:

Wed Oct  5 08:05:29 EDT 2016 c460c002: status=booted  
...
Wed Oct  5 08:06:49 EDT 2016 c460c002: status=booted  
...
Wed Oct  5 08:08:58 EDT 2016 c460c002: status=netbooting  
...
Wed Oct  5 08:12:45 EDT 2016 c460c002: status=failed
...

The shutdown appears to be completly unnoticed by xCAT until the node reaches out and requests it's boot image.

This causes problems for us when we attempt to do a reboot and then the shutdown hangs, there is nothing in the xcat status that tell that we are in this state.

**Comment by tingtli** [comment]
I remember we have a powering-off state when we do some test but not sure why there is no in ralph's environment. Is it because the time  framework? @immarvin

**Comment by ralphbellofatto** [comment]
hmm...

observations:
```
[root@c460mgt01 otherpkgs]# rpower c460c002 off
c460c002: off
[root@c460mgt01 otherpkgs]# nodestat c460c002
c460c002: noping

[root@c460mgt01 otherpkgs]# lsdef c460c002 -i status
Object name: c460c002
    status=powering-off

```

so, the rpower off does get noticed, but not by nodestat..

however
```
rpower c460c002 on
# wait for boot to complete...

[root@c460mgt01 otherpkgs]# nodestat c460c002
c460c002: sshd
[root@c460mgt01 otherpkgs]# lsdef c460c002 -i status
Object name: c460c002
    status=booted

[root@c460mgt01 otherpkgs]# xdsh c460c002 reboot

[root@c460mgt01 otherpkgs]# nodestat c460c002
c460c002: noping
[root@c460mgt01 otherpkgs]# lsdef c460c002 -i status
Object name: c460c002
    status=booted

```

The system did not notice the system rebooting when the reboot request happened.

So we see nodestat, noping, but status=booted, which looks like a problem but in reality it is just normal operations..

**Comment by immarvin** [comment]
hi @ralphbellofatto , for server shutdown/reboot operation , currently xCAT can only update the node status with the process issued with "rpower/rnetboot". For the process initiated on the operating system with "shutdown/reboot", we need to look for the time in "shutdown" to feedback status to MN.

**Comment by ralphbellofatto** [comment]
I know that xcat communicates its final boot status (basically the return code from when init.rd has finished running all its initialization routines (or at least when xcat finishes all its postboot scripts.

Is it possible to have a similar communication hook put into the shutdown code fired off by init.d/system,d to report that status back to xcat?


I think thje communication channel is already in place.

**Comment by daniceexi** [comment]
The philosophy of xCAT is that don't make change to the compute node. So currently xCAT does not make any hack for the compute node itself. 

If it's necessary, could you accept to make a postscript to customize the compute node?

**Comment by ralphbellofatto** [comment]
xcat already inserted postboot code that alerts xcat of the status change to either booted, or failed.

Why can't that same mechinims be hooked into the shutdown sequence.

To do this, we would not only have to insert the hook ourselves, but we would have to probably hack xcat to reflect this in the status and nodestat..

**Comment by daniceexi** [comment]
@immarvin Could you take a look the effort to insert a reboot/shutdown hook?

**Comment by immarvin** [comment]
hi @daniceexi , we might need to convert /etc/init.d/xcatpostinit1 to systemd unit to make sure the xcatpostinit1 service be stopped before network service is stopped.

**Comment by immarvin** [comment]
working on the PR

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2055/files

**Comment by immarvin** [comment]
hi @ralphbellofatto , I verified this PR on redhat 7.3 GA, I will close this , please reopen it if you find the issue again

**Comment by ralphbellofatto** [comment]
This does not seem to be fix din the latest version, we still don't see any change either in netstat or lsdef -i status when the shutdown happens.

I performed the following to update.
```
yum update xCAT*
yum update *xCAT*
systemctl restartxcat
genimage rh72_op5_compute
packimage rh72_op5_compute
```

Then rebooted c460c001 once just to clear things out.

I used this on another terminal session to monitor the boot status:
```
N=c460c001
while true; do
 echo "$(date) $(lsdef $N -c -i status)" $(nodestat $N) 
 sleep 5;
done
```

And subsequently rebooted the compute node.
[root@c460mgt01 ralphbel]# echo  $(date); xdsh c460c001 reboot
Tue Nov 8 08:41:07 EST 2016
c460c001: Connection to c460c001 closed by remote host.
```

```

Tue Nov  8 08:40:37 EST 2016 c460c001: status=booted c460c001: sshd
...
Tue Nov  8 08:41:05 EST 2016 c460c001: status=booted c460c001: sshd
Tue Nov  8 08:41:11 EST 2016 c460c001: status=booted c460c001: noping
...
Tue Nov  8 08:43:43 EST 2016 c460c001: status=booted c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 08:43:48 EST 2016 c460c001: status=booted c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 08:43:54 EST 2016 c460c001: status=booted c460c001: noping
Tue Nov  8 08:44:02 EST 2016 c460c001: status=booted c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 08:46:58 EST 2016 c460c001: status=netbooting c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 08:47:04 EST 2016 c460c001: status=netbooting c460c001: sshd
Tue Nov  8 08:48:17 EST 2016 c460c001: status=netbooting c460c001: sshd
Tue Nov  8 08:48:22 EST 2016 c460c001: status=booted c460c001: sshd
```

**Comment by cxhong** [comment]
Ralph tested and it didn't work.  reopen this issue for him

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/2109

**Comment by immarvin** [comment]
hi @ralphbellofatto , the fix has been merged, please verify it.

**Comment by ralphbellofatto** [comment]
after snagging the update we now see:

```
Tue Nov  8 12:05:28 EST 2016 c460c001: status=booted c460c001: sshd
Tue Nov  8 12:05:34 EST 2016 c460c001: status=powering-off c460c001: noping
Tue Nov  8 12:05:41 EST 2016 c460c001: status=powering-off c460c001: noping

Tue Nov  8 12:08:06 EST 2016 c460c001: status=powering-off c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 12:08:23 EST 2016 c460c001: status=powering-off c460c001: noping
Tue Nov  8 12:08:30 EST 2016 c460c001: status=powering-off c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 12:08:37 EST 2016 c460c001: status=netbooting c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 12:08:43 EST 2016 c460c001: status=netbooting c460c001: netboot rhels7.2-ppc64le-compute
Tue Nov  8 12:11:38 EST 2016 c460c001: status=netbooting c460c001: sshd
Tue Nov  8 12:11:43 EST 2016 c460c001: status=netbooting c460c001: sshd
Tue Nov  8 12:12:51 EST 2016 c460c001: status=netbooting c460c001: sshd
Tue Nov  8 12:12:56 EST 2016 c460c001: status=booted c460c001: sshd
Tue Nov  8 12:13:02 EST 2016 c460c001: status=failed c460c001: sshd
Tue Nov  8 12:13:08 EST 2016 c460c001: status=failed c460c001: sshd

```
Was node state supposed to show any indication of the booting situation ??

I'm going to have to investigate why we suddenly got the failed status.

not sure it is related to this change.

**Comment by ralphbellofatto** [comment]
the failed status was not due to the change, but the question for the nodestat still stands...

**Comment by whowutwut** [comment]
@immarvin @zet809  Can we get a response for Ralph's question above?  If it is a separate issue, please open another Issue so we can close this one out.

**Comment by immarvin** [comment]
hi @ralphbellofatto , the node status problem has been fixed in xCAT 2.12.4 release https://github.com/xcat2/xcat-core/pull/2137. 

Currently, the ``nodestat``  command is only reserved for internal use.  xCAT provides a tool "xcatprobe osdeploy"  to obtain the detailed information on the os provisioning. Currently, only diskful is supported .

**Comment by ralphbellofatto** [comment]
That statement about node state seems to contradict the documents published about node state here:

http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man1/nodestat.1.html

**Comment by ralphbellofatto** [comment]
Also, this state looks a bit inconsistant:

```
Tue Nov 15 08:40:12 EST 2016 c460c001: status=powering-off c460c001: netboot rhels7.2-ppc64le-compute
```

Looking at osdeploy:
```
[root@c460mgt01 10.1.0.2_ESP]# xcatprobe osdeploy -n c460c001
The install NIC in current server is enP1p12s0f0.1@enP1p12s0f0                                [INFO]
All nodes to be deployed are valid                                                            [ OK ]
-------------------------------------------------------------
Start capturing every message during OS provision process....
-------------------------------------------------------------

[c460c001] Receive DHCPDISCOVER via enP1p12s0f0.1
[c460c001] Receive DHCPDISCOVER via enP1p12s0f0.1
[c460c001] Send DHCPOFFER on 10.1.1.1 back to 70:e2:84:14:0e:58 via enP1p12s0f0.1
[c460c001] Send DHCPOFFER on 10.1.1.1 back to 70:e2:84:14:0e:58 via enP1p12s0f0.1
[c460c001] DHCPREQUEST for 10.1.1.1 (10.1.0.1) from 70:e2:84:14:0e:58 via enP1p12s0f0.1
[c460c001] DHCPREQUEST for 10.1.1.1 (10.1.0.1) from 70:e2:84:14:0e:58 via enP1p12s0f0.1
[c460c001] Send DHCPACK on 10.1.1.1 back to 70:e2:84:14:0e:58 via enP1p12s0f0.1
[c460c001] Via HTTP get /tftpboot/petitboot/c460c001
[c460c001] Send DHCPACK on 10.1.1.1 back to 70:e2:84:14:0e:58 via enP1p12s0f0.1
[c460c001] Via HTTP get /tftpboot/xcat/osimage/rh72_op5_compute/kernel
[c460c001] Via HTTP get /tftpboot/xcat/osimage/rh72_op5_compute/initrd-stateless.gz
```

It would be good if these messages had timestamps, as the time these events and their temporial relationship is frequently important.

It looks like the lsdef -i status field does not know when we entered the "netboot" state...

**Comment by hu-weihua** [comment]
Hi @ralphbellofatto,  thank you very much for your feedback of xCAT Probe. ``xcatprobe osdeploy `` is developed for diskful provision, can't support diskless provision right now. We will take it into account when we move xCAT Probe forward next, including timestamps stuff.  thanks again.

**Comment by ralphbellofatto** [comment]
so what is recommended for monitoring diskless boot?  and what is the purpose of nodestat, there is nothing in the document that says that it should not be reflecting the current status of the node.

**Comment by immarvin** [comment]
hi @ralphbellofatto , 
since the node status reporting is done inside the initrd, so the node status will not be changed to "netbooting" until the whole netbooting process run into the initrd after it is downloaded and extracted.

**Comment by immarvin** [comment]
currently , you can trace the status of a diskless node with "lsdef <node> -i status" on 2 checkpoints(netbooting and booted). 
"xcatprobe osdeploy" might provide more detailed information, but the diskless support is not completed yet.
@daniceexi , would you please provide some information on the intent of "nodestat" command? I know that it can be used to pull some progress information during the diskful provision, but I do not think "nodestat"  will provide the monitoring information for a diskless provision.

**Comment by tingtli** [comment]
@neo954  Please review and verify this bug. Thanks!

**Comment by neo954** [comment]
Verified with the 2.12.4 GA build. This issue was fixed. I will close this issue.
