### ISSUE TITLE
[Customer]`nodeset $node osimage=$image` should clean out keys for $node from `~root/.ssh/known_hosts`

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#280]
Re-imaging a node always changes the ssh host key of the node, and will always trigger the `ssh` `man-in-the-middle` warning. A better solution would be to `remove the offending keys` from the `known_hosts` file.

**Comment by daniceexi** [comment]
@samveen The issue has been fixed by pull request #542. Please confirm.

**Comment by samveen** [comment]
@daniceexi Looks like the fix should work. Closing ticket.

**Comment by whowutwut** [comment]
Using the latest build, we still see this issue in 2.12.1.... 
```
[root@fs1 ~]# ssh c910f05c31
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
46:5d:dd:3f:58:b5:fc:7f:53:4e:6a:73:ed:62:8f:5b.
Please contact your system administrator.
Add correct host key in /root/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /root/.ssh/known_hosts:22
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
[root@c910f05c31 ~]# ```

Going to reopen....

**Comment by gurevichmark** [comment]
I am wondering is the same should be done for issue #450. If user issues `nodeset <name> offline` should we remove the entry from **known_hosts** ?

**Comment by whowutwut** [comment]
Yes, good point. I think we should.  If offline means we need to re-provision when bringing back online, the host key will change.

**Comment by daniceexi** [comment]
``offline`` means deconfigure the provision configuration. But the node is still in power on status. Do we want this impacts the xdsh command?

**Comment by whowutwut** [comment]
@daniceexi  I don't think we should allow `nodeset <noderange> offline` if the node is actually running, maybe need to have a rpower check against the node...

**Comment by daniceexi** [comment]
Two points here, we should consider them separately:
* User may run ``nodeset offline`` after the node deployment and transfer the installed node to other department to use. I think we need define the ``offline`` more accurately.
* ``nodeset offline`` is used to deconfigure the configuration for node to perform the os deployment. But the host key in the authorized_keys is just used for the user to connect to another server. These two things may have not tight connection.

**Comment by whowutwut** [comment]
The fix that @cxhong  made was for the node that was provisioned.  The issue here is that the mgmt node needs to clear out the key in `~/.ssh/known_hosts`.  The `ssh-keygen -R <node>` would  clear it , but when is the best way to do this....? 

1) if we do it on the `nodeset <node> osimage=...`, the user can still ssh to the existing node before starting the re-provision and the old key will get stored in the `known_hosts` file again.  
2) Another thought is that we could only do this key cleanup when the admin uses the `rinstall` command to reinstall the nodes

**Comment by daniceexi** [comment]
xCAT has a dedicated command ``makeknownhosts`` to handle the known host keys.

Yes, use ``rinstall`` is a choice. But if the issue has been fixed through @cxhong 's change, that means user would not encounter this problem any more. If user really want to handle 'known hosts' entry, should we recommend them to handle it by themselves through ``makeknownhosts`` command?

**Comment by cxhong** [comment]
I couldn't recreate this issue on ppc64le or x86 VMs.  I think this is issue caused by MN on some bad state while node provisioned (nslookup failed is one of case).  makeknownhosts or updatenode -K will get rid of "man in the middle" message.

**Comment by cxhong** [comment]
@whowutwut @daniceexi  how we handle this issue?  rinstall  or run makeknownhosts command manually?

**Comment by daniceexi** [comment]
I recommend to run ``makeknownhosts`` by customer.

**Comment by cxhong** [comment]
can we close this issue then if we recommend to run makeknowhosts by customer?

**Comment by daniceexi** [comment]
I think so.
