### ISSUE TITLE
[OpenBMC] Reduce rflash verbose output with option and do not interact with the Progress endpoint

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4287]
Seeing the following issues when flashing FW on clusters in-house...
see: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW408030 for more details... 
```
# rflash cn01,cn03,cn04,cn05,cn08 /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar -a
cn08: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn04: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn03: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn01: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn05: Uploading /firmware/Witherspoon/OP910_1742E/obmc-phosphor-image-witherspoon.ubi.mtd.tar ...
cn08: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn04: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn01: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn08: Could not find ID for firmware ibm-v2.0-0-r5-0-g2fd869c to activate, waiting 10 seconds and retry...
cn04: rflash started, please wait...
cn05: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn04: Error: Path or object not found: /xyz/openbmc_project/software/a625b9dd
cn01: rflash started, please wait...
cn03: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c
cn01: Activating firmware . . . 30%
cn05: rflash started, please wait...
cn05: Activating firmware . . . 30%
cn03: rflash started, please wait...
cn03: Activating firmware . . . 10%
cn08: rflash started, please wait...
cn08: Activating firmware . . . 10%
cn01: Error: Path or object not found: /xyz/openbmc_project/software/5901a2d6
cn05: Activating firmware . . . 30%
cn03: Activating firmware . . . 30%
cn08: Activating firmware . . . 30%
...
cn05: Activating firmware . . . 30%
cn08: Activating firmware . . . 30%
cn03: Firmware activation Successful.
cn05: Activating firmware . . . 30%
cn08: Firmware activation Successful.
cn05: Firmware activation Successful.
```

somewhat related to #4246 

However, I'd like to open this issue to track the following... 

1. Implement a verbose option for rflash, without verbose
   - without verbose, 
       - do not print progress, don't even call that API function 
        - do not print `Could not find ID for...` message... 

Doing the above will reduce some of the verbose output.  

2. I'd like to print the ID out for the FW, since we have seen some bugs in the hashing algorithm they are using: `Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c (ID: <ID>)`

3. Then with those changes, we should see if the Error messages still come out...  I think we should test against the Status Change from Activating -> Active/Error instead of checking Progress. The Progress Endpoint is not reliable right now

**Comment by whowutwut** [comment]
Even though we had those errors, the FW actually activated on all 5... 
```
[vhu@c910loginx01 tmp]$ grep v2.0 flash.output2
cn08: 5901a2d6 BMC     Active(*)  ibm-v2.0-0-r5-0-g2fd869c
cn05: 5901a2d6 BMC     Active(*)  ibm-v2.0-0-r5-0-g2fd869c
cn03: 5901a2d6 BMC     Active(*)  ibm-v2.0-0-r5-0-g2fd869c
cn04: 5901a2d6 BMC     Active(*)  ibm-v2.0-0-r5-0-g2fd869c
cn01: a625b9dd BMC     Active(*)  ibm-v2.0-0-r5-0-g2fd869c
```
hash is different on cn01...  that's why I want to print out the hash for our own debug information. 

However, require #3671 to store log messages in `/var/log/xcat/rflash` for that to be useful...

**Comment by gurevichmark** [comment]
Fixed in PR #4303 

1. Most messages are only displayed with verbose option.
2. ID added to the output of `Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r5-0-g2fd869c (ID: <ID>)`
3. "Progress" is just one of the attributes that comes back when checking the state of the activation. Same API is called to get the status "Activating", "Active" or "Failed".

**Comment by whowutwut** [comment]
I still don't think we have a good way to prevent the initial issue, because it seems like there's some intermittent time when the endpoint goes missing in the firmware causing that error.  The error is handled as part of the openbmc xCAT framework and it's very hackish to detect that error, then do another query to see if the endpoint comes back...

**Comment by whowutwut** [comment]
@gurevichmark I tried the latest....  let's talk about this next week...  sorry to keep going back and forth... but just looking at usability...   

Without verbose, there's a delay before the first message come back...   it was maybe 5 seconds  (Yes it's short but it's still a bit uncomfortable and I start thinking.. uh.. what's going on?) and worry that something hung... 

```
[root@briggs01 910.1746.20171116b_1742Ed]# rflash $NODE -u ./obmc-phosphor-image-witherspoon.ubi.mtd.tar
# DELAY HERE.... 
mid05tor12cn18: Firmware upload successful. Use -l option to list.
mid05tor12cn02: Firmware upload successful. Use -l option to list.
```

And with verbose....we get the output... 
```
[root@briggs01 910.1746.20171116b_1742Ed]# rflash $NODE -u ./witherspoon.pnor.squashfs.tar -V
mid05tor12cn18: [briggs01]: Uploading /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/./witherspoon.pnor.squashfs.tar ...
mid05tor12cn02: [briggs01]: Uploading /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/./witherspoon.pnor.squashfs.tar ...
mid05tor12cn18: [briggs01]: Firmware upload successful. Use -l option to list.
mid05tor12cn02: [briggs01]: Firmware upload successful. Use -l option to list.
```

Perhaps with and without verbose, we should print a single message immediately to show the user that xCAT is started doing something...

```
[root@briggs01 910.1746.20171116b_1742Ed]# rflash $NODE -u ./obmc-phosphor-image-witherspoon.ubi.mtd.tar
Uploading /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/./witherspoon.pnor.squashfs.tar, please wait...
...
...
```

I just don't like this strange delays after running commands.

**Comment by whowutwut** [comment]
Same comment on the activation....
```
[root@briggs01 910.1746.20171116b_1742Ed]# rflash $NODE -a 82087175

```

this is even longer yet and feels like something is hung...  A single message would be better than nothing. 

```
[root@briggs01 910.1746.20171116b_1742Ed]# rflash $NODE -a 82087175
Activating  < > blah  blah blah, please wait.... 
```

**Comment by whowutwut** [comment]
A lot of the output for rflash has changed, Thanks @gurevichmark @xuweibj , let's close this and get feedback from users on what helps, what doesn't... and take it from there.
