### ISSUE TITLE
[FVT]copycds does not put files under correct directory and does not create correct image for SDK iso

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#654]
Test OS:  SLES 11 SP4
Test xCAT version: Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)
How to reproduce: 
1. Install and config xCAT MN
2. run "copycds"

```
c693xx2:/iso # copycds SLE-11-SP4-SDK-DVD-x86_64-GM-DVD1.iso
Copying media to /install/sles11/x86_64/sdk1
Media copy operation successful
```

3. Check the file is placed under  /install/sles11/x86_64/sdk1. It should be placed under  /install/sles11.4/x86_64/sdk1

```
c693xx2:/iso # ls /install/sles11/x86_64/
.fingerprint  sdk1
```

4. The image is also not correct.

```
c69xxx:/iso # tabdump osimage
#imagename,groups,profile,imagetype,description,provmethod,rootfstype,osdistroname,osupdatename,cfmdir,osname,osvers,osarch,synclists,postscripts,postbootscripts,serverrole,isdeletable,kitcomponents,comments,disable
"sles11-x86_64-install-compute",,"compute","linux",,"install",,"sles11-x86_64",,,"Linux","sles11","x86_64",,,,,,,,
"sles11-x86_64-install-service",,"service","linux",,"install",,"sles11-x86_64",,,"Linux","sles11","x86_64",,,,,,,,
"sles11-x86_64-netboot-compute",,"compute","linux",,"netboot",,"sles11-x86_64",,,"Linux","sles11","x86_64",,,,,,,,
```

**Comment by immarvin** [comment]
@penguhyang ,can you take a look at this?

**Comment by whowutwut** [comment]
FYI, This might already be fixed in 2.11/2.12 by @pdlun92 in Issues #271

**Comment by immarvin** [comment]
hi @tingtli , can you verify this with 2.11/2.12?

**Comment by immarvin** [comment]
@whowutwut , this problem still exist in :
````

c910f02c09p05:~ # lsxcatd -v
Version 2.12 (git commit 9f844a62f42ba889578b99ad7062a14ea1e7f27e, built Sun Jan 24 15:30:48 EST 2016)
c910f02c09p05:~ # 
````

@penguhyang has checked in the fix in https://github.com/xcat2/xcat-core/pull/666

**Comment by whowutwut** [comment]
@immarvin  @penguhyang  Thanks for checking.   I think for the later releases of SLES they changed the wording of the identifier we are checking.. 

SLES11 SP4 SDK: ``SUSE Linux Enterprise Software Development Kit 11 SP4``
SLES 12 SDK : `` cpe:/o:suse:sle-sdk:12:sp1,SUSE Linux Enterprise Software Development Kit 12 SP1``

For sles 12 we checked ``sdk:12 sp1`` instead of the ``12 SP1`` tag..
I wonder if we should merge @penguhyang fix forward?

**Comment by tingtli** [comment]
Verified on xcat 2.12
[root@c910f02c01p15 iso]# copycds SLE-12-SP1-SDK-DVD-x86_64-GM-DVD1.iso
Copying media to /install/sles12.1/x86_64/sdk1
Media copy operation successful
[root@c910f02c01p15 iso]# copycds SLE-12-SDK-DVD-ppc64le-GM-DVD1.iso
Copying media to /install/sles12/ppc64le/sdk1
Media copy operation successful
